name: ankylo_cup
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.22.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_app_check: ^0.3.1+7
  google_sign_in: ^6.2.2
  sensors_plus: ^6.1.1
  grpc: ^4.0.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
